/**
 * exportUtils.js
 * Handles file downloads and export artifact generation.
 */

/**
 * Trigger a browser download of a Blob.
 * @param {Blob} blob
 * @param {string} filename
 */
export function downloadBlob(blob, filename) {
  try {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (err) {
    throw new Error(`Export failed: ${err.message}`)
  }
}

/**
 * Export model as a simulated pickle file.
 */
export function exportPickle(dataset, model) {
  const content = `# Simulated Pickle Export
# This is a placeholder for a real pickle file.
# In production, use: import pickle; pickle.dump(model, open('model.pkl', 'wb'))

# Model: ${model?.name || 'Unknown'}
# Dataset: ${dataset?.name || 'Unknown'}
# Accuracy: ${model?.accuracy?.toFixed(4) || 'N/A'}
# Trained on: ${new Date().toISOString()}

# To load this model:
# import pickle
# with open('${dataset?.name || 'model'}_model.pkl', 'rb') as f:
#     model = pickle.load(f)
`
  const blob = new Blob([content], { type: 'application/octet-stream' })
  downloadBlob(blob, `${dataset?.name || 'model'}_model.pkl`)
}

/**
 * Export model as a simulated joblib file.
 */
export function exportJoblib(dataset, model) {
  const content = `# Simulated Joblib Export
# This is a placeholder for a real joblib file.
# In production, use: from joblib import dump; dump(model, 'model.joblib')

# Model: ${model?.name || 'Unknown'}
# Dataset: ${dataset?.name || 'Unknown'}
# Accuracy: ${model?.accuracy?.toFixed(4) || 'N/A'}
# Trained on: ${new Date().toISOString()}

# To load this model:
# from joblib import load
# model = load('${dataset?.name || 'model'}_model.joblib')
`
  const blob = new Blob([content], { type: 'application/octet-stream' })
  downloadBlob(blob, `${dataset?.name || 'model'}_model.joblib`)
}

/**
 * Generate FastAPI endpoint code for model serving.
 * @param {Dataset} dataset
 * @param {ModelCard} model
 * @returns {string}
 */
export function generateFastAPICode(dataset, model) {
  const numericFeatures = dataset?.columns
    ?.filter((c) => c.dtype === 'numeric' && c.name !== dataset.columns[dataset.columns.length - 1]?.name)
    ?.map((c) => c.name) || ['feature1', 'feature2', 'feature3']

  const modelName = model?.name || 'YourModel'
  const datasetName = dataset?.name || 'dataset'

  const pydanticFields = numericFeatures
    .map((f) => `    ${f.replace(/[^a-zA-Z0-9_]/g, '_')}: float`)
    .join('\n')

  const featureList = numericFeatures
    .map((f) => `        ${f.replace(/[^a-zA-Z0-9_]/g, '_')}=data.${f.replace(/[^a-zA-Z0-9_]/g, '_')}`)
    .join(',\n')

  return `# FastAPI Endpoint for ${modelName}
# Generated by AI Agent for Data Scientists
# Dataset: ${datasetName}

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from joblib import load
import numpy as np
import uvicorn

# Initialize FastAPI app
app = FastAPI(
    title="${modelName} Prediction API",
    description="ML model serving endpoint for ${datasetName}",
    version="1.0.0"
)

# Load the trained model
# Ensure '${datasetName}_model.joblib' is in the same directory
try:
    model = load('${datasetName}_model.joblib')
except FileNotFoundError:
    raise RuntimeError("Model file not found. Please train and export the model first.")


# Input schema (Pydantic BaseModel)
class PredictionInput(BaseModel):
${pydanticFields}

    class Config:
        schema_extra = {
            "example": {
${numericFeatures.map((f) => `                "${f.replace(/[^a-zA-Z0-9_]/g, '_')}": 0.0`).join(',\n')}
            }
        }


# Output schema
class PredictionOutput(BaseModel):
    prediction: float
    model_name: str
    confidence: float


@app.get("/")
def root():
    return {"message": "ML Model API is running", "model": "${modelName}"}


@app.get("/health")
def health_check():
    return {"status": "healthy", "model_loaded": model is not None}


@app.post("/predict", response_model=PredictionOutput)
def predict(data: PredictionInput):
    """
    Make a prediction using the trained ${modelName} model.
    """
    try:
        # Prepare feature array
        features = np.array([[
${featureList}
        ]])

        # Generate prediction
        prediction = model.predict(features)[0]

        # Get confidence (probability for classifiers)
        confidence = 0.85  # Default confidence
        if hasattr(model, 'predict_proba'):
            proba = model.predict_proba(features)[0]
            confidence = float(max(proba))

        return PredictionOutput(
            prediction=float(prediction),
            model_name="${modelName}",
            confidence=confidence
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
    # Access API docs at: http://localhost:8000/docs
`
}

/**
 * Generate a plain-text model report.
 * @param {Dataset} dataset
 * @param {CleaningStep[]} cleaningSteps
 * @param {ModelCard} model
 * @param {TrainingResults} trainingResults
 * @returns {string}
 */
export function generateReport(dataset, cleaningSteps, model, trainingResults) {
  const separator = '═'.repeat(60)
  const line = '─'.repeat(60)

  const cleaningList = cleaningSteps?.length > 0
    ? cleaningSteps.map((s, i) => `  ${i + 1}. ${s.operation}${s.column ? ` on column "${s.column}"` : ''}`).join('\n')
    : '  No cleaning steps applied'

  return `${separator}
AI AGENT FOR DATA SCIENTISTS — MODEL REPORT
Generated: ${new Date().toLocaleString()}
${separator}

DATASET INFORMATION
${line}
Name:             ${dataset?.name || 'N/A'}
Rows:             ${dataset?.rowCount || 0}
Columns:          ${dataset?.colCount || 0}
Missing Values:   ${dataset?.missingCount || 0}
Duplicate Rows:   ${dataset?.duplicateCount || 0}
Quality Score:    ${dataset?.qualityScore || 0}/100

COLUMN DETAILS
${line}
${dataset?.columns?.map((c) => `  ${c.name.padEnd(20)} ${c.dtype.padEnd(15)} Missing: ${c.missingCount}`).join('\n') || '  N/A'}

APPLIED CLEANING STEPS
${line}
${cleaningList}

SELECTED MODEL
${line}
Model Name:       ${model?.name || 'N/A'}
Problem Type:     ${model?.type || 'N/A'}
Justification:    ${model?.justification || 'N/A'}

PERFORMANCE METRICS
${line}
Accuracy:         ${model?.accuracy?.toFixed(4) || 'N/A'}
Precision:        ${model?.precision?.toFixed(4) || 'N/A'}
Recall:           ${model?.recall?.toFixed(4) || 'N/A'}
F1 Score:         ${model?.f1?.toFixed(4) || 'N/A'}

TRAINING RESULTS
${line}
Final Accuracy:   ${trainingResults?.finalAccuracy?.toFixed(4) || 'N/A'}
Training Duration: ${trainingResults?.duration?.toFixed(1) || 'N/A'} seconds
Epochs Completed: ${trainingResults?.epochs?.length || 0}
Validation Accuracy: ${trainingResults?.validationMetrics?.accuracy?.toFixed(4) || 'N/A'}
Validation Loss:  ${trainingResults?.validationMetrics?.loss?.toFixed(4) || 'N/A'}

EPOCH LOG
${line}
${trainingResults?.epochs?.map((e) =>
  `  Epoch ${String(e.epoch).padStart(2)}: Loss=${e.loss.toFixed(4)}  Accuracy=${e.accuracy.toFixed(4)}`
).join('\n') || '  No training data available'}

${separator}
Report generated by AI Agent for Data Scientists
${separator}
`
}

/**
 * Download the model report as a text file.
 */
export function downloadReport(dataset, cleaningSteps, model, trainingResults) {
  const report = generateReport(dataset, cleaningSteps, model, trainingResults)
  const blob = new Blob([report], { type: 'text/plain' })
  downloadBlob(blob, `${dataset?.name || 'model'}_report.txt`)
}

export default { downloadBlob, exportPickle, exportJoblib, generateFastAPICode, generateReport, downloadReport }
